<h2>Welcome to Bluethink.com</h2>

<form action="<?php echo $block->getFormAction() ?>" method="post">
    <label for="">Name</label>
    <input type="text" id="name" name="name"><br><br>

    <label for="">Email</label>
    <input type="email" id="email" name="email"><br><br>

    <label for="">Password</label>
    <input type="password" id="password" name="password"><br><br>

    <label for="">Confirm Password</label>
    <input type="password" id="c_password"><br><br>
    <input type="submit" id="btn">
</form> 