<?php
/**
* @var $block \Bluethink\CustomSection\Block\Adminhtml\Order\View\Tab\OrderStatus
*/
$orderId=$block->getOrderIncrementId();
$orderstatus = $block->getOrderStatusOptions();
?>

<div class="fieldset-wrapper order-information">
   <div>
       <h2>Bluethink</h2>
   </div>
   <div class="fieldset-wrapper-title">
       <span class="title"><?php /* @escapeNotVerified */
           echo __('Information for new Order tab') ?></span>
   </div>
   <table class="admin__table-secondary">
       <tbody>
       <?php echo $block->getChildHtml(); ?>
       <tr>
           <th><?php /* @escapeNotVerified */
               echo __('Order ID:') ?></th>
           <td><?php echo $orderId; ?></td>
       </tr>
       <tr>
           <th><?php /* @escapeNotVerified */
               echo __('Current Order State:') ?></th>
           <td><?php  echo $block->getOrderState($orderId); ?></td>
       </tr>
       <tr>
           <th><?php /* @escapeNotVerified */
               echo __('Current Order Status:') ?></th>
           <td><?php echo $block->getOrderStatus($orderId); ?></td>
       </tr>
       
       <tr>
           <th><?php /* @escapeNotVerified */
               echo __('Change Order Status:') ?></th>
           <td>
           <form name="addData" method="post" id="addData" class="form"
              action="" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
              data-mage-init='{"validation":{}}'>
              <input type="hidden" name="order_id" value='<?php echo $orderId; ?>'>
               <select name="order_status" id="data" class="admin__control-select">
                    <?php
                    foreach($orderstatus as $key){
                            ?>
                            <option value="<?php echo $key['value'];?>"><?php echo $key['label'];?></option>
                            <?php
                        
                    }
                    ?>
                </select>
                <button type="button" class="accc" title="Save" id="submitajax">Save</button>
                </form>

            </td>
       </tr>
     
       </tbody>
   </table>
   <!-- <div id="message" style="background-color:#fffbbb; width:100%; padding:10px"></div> -->
</div> 
<script>
    require(["jquery"],function($) {
      jQuery(document).on('click','#submitajax',function() {
        //   var dataForm = document.getElementById("data").value;
             event.preventDefault();
             var dataForm = $("form").serialize();
                //  var param = dataForm.serialize();
                 alert(dataForm);
                 jQuery.ajax({
                         showLoader: true,
                         url: '<?php echo $block->getUrl('customsection/index/save') ?>',
                         data: dataForm,
                         type: "POST"
                     }).done(function (data) {
                         if(data.message==="Order status Updated Successfully")
                         {
                           
                         }else{

                         }
                        // jQuery('.note').html(data);
                        // jQuery('.note').css('color', 'red');
                        //  document.getElementById("contact-form").reset();
                         return true;
                     });
                 
             });
        });
</script>